Repository HugoGresse/OpenPlanner, pull requests merged in 2023-03, with the labels that each got.

#4 Import from ConferenceHall
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  public/logos/conference-hall.png
  src/ConferenceHallEvents.tsx
  src/conferencehall/ConferenceHallEventsPicker.tsx
  src/conferencehall/RequireConferenceHallLogin.tsx
  src/conferencehall/authConferenceHall.ts
  src/conferencehall/components/ConferenceHallEventItem.tsx
  src/conferencehall/components/ConferenceHallOrganizationWithEventsItem.tsx
  src/conferencehall/components/ConferenceHallProposalsPicker.tsx
  src/conferencehall/components/ConferenceHallProposalsPickerItem.tsx
  src/conferencehall/firebase/authConferenceHall.ts
  src/conferencehall/firebase/conferenceHallFirebase.ts
  src/conferencehall/firebase/getConferenceHallSpeakers.ts
  src/conferencehall/getConferenceHallEvents.ts
  src/conferencehall/hooks/useConferenceHallEvents.tsx
  src/conferencehall/hooks/useConferenceHallOrganization.tsx
  src/conferencehall/hooks/useConferenceHallOrganizationEvents.tsx
  src/conferencehall/hooks/useConferenceHallProposals.tsx
  src/conferencehall/initConferenceHall.ts
  src/events/EventsListItem.tsx
  src/events/EventsScreen.tsx
  src/events/NewEventCreatedDialog.tsx
  src/events/NewEventDialog.tsx
  src/events/actions/addNewEvent.ts
  src/services/converters.ts
  src/services/firebase.ts
  src/types.ts
Labels: enhancement

#5 Prevent multiple networks call when selecting import proposals states
  src/App.tsx
  src/conferencehall/components/ConferenceHallProposalsPicker.tsx
  src/conferencehall/components/ConferenceHallProposalsPickerConnected.tsx
  src/events/NewEventDialog.tsx
Labels: bug

#6 Implement Event admin layout
  package-lock.json
  package.json
  src/App.tsx
  src/components/NestedRoutes.tsx
  src/events/list/EventsLayout.tsx
  src/events/list/EventsListItem.tsx
  src/events/list/EventsScreen.tsx
  src/events/new/NewEventCreatedDialog.tsx
  src/events/new/NewEventDialog.tsx
  src/events/page/EventLayout.tsx
  src/events/page/EventRouter.tsx
  src/events/page/EventScreenMenuItems.tsx
  src/events/page/EventSponsors.tsx
  src/services/hooks/useEvent.ts
Labels: enhancement

#7 WIP on settings edition
  package-lock.json
  package.json
  src/events/list/EventsScreen.tsx
  src/events/page/EventRouter.tsx
  src/events/page/EventSponsors.tsx
  src/events/page/settings/EventSettings.tsx
  src/events/page/settings/components/TrackFields.tsx
  src/events/page/settings/components/WebhooksFields.tsx
  src/services/hooks/useEvent.ts
  src/types.ts
  src/utils/sleep.ts
  src/utils/slugify.ts
Labels: enhancement

#8 Add dates edition
  package-lock.json
  package.json
  src/events/page/settings/EventSettings.tsx
  src/events/page/settings/components/TrackFields.tsx
  src/events/page/settings/components/WebhooksFields.tsx
  src/services/converters.ts
  src/types.ts
  src/utils/diffDays.ts
Labels: enhancement

#11 Schedule edition
  .gitignore
  firestore.rules
  package-lock.json
  package.json
  src/App.tsx
  src/components/ConfirmDialog.tsx
  src/events/actions/addNewEvent.ts
  src/events/actions/updateSession.ts
  src/events/new/NewEventDialog.tsx
  src/events/page/EventLayout.tsx
  src/events/page/EventRouter.tsx
  src/events/page/EventSponsors.tsx
  src/events/page/schedule/DaySchedule.tsx
  src/events/page/schedule/DayScheduleHeader.tsx
  src/events/page/schedule/EventSchedule.tsx
  src/events/page/schedule/NoDatesSessionsPicker.tsx
  src/events/page/schedule/components/CalendarSlot.tsx
  src/events/page/schedule/components/CalendarTrackSlot.tsx
  src/events/page/schedule/components/SessionCard.tsx
  src/events/page/schedule/scheduleConstants.ts
  src/events/page/settings/EventSettings.tsx
  src/services/converters.ts
  src/services/firebase.ts
  src/services/hooks/useSessions.ts
  src/services/hooks/useSpeakers.ts
  src/types.ts
  src/utils/diffDays.ts
  src/utils/generateTimeSlots.ts
  src/utils/timeFormats.ts
Labels: enhancement

#14 List sessions + fix some stuff
  src/events/actions/addNewEvent.ts
  src/events/page/EventLayout.tsx
  src/events/page/EventRouter.tsx
  src/events/page/EventScreenMenuItems.tsx
  src/events/page/schedule/NoDatesSessionsPicker.tsx
  src/events/page/schedule/components/SessionCard.tsx
  src/events/page/sessions/EventSession.tsx
  src/events/page/sessions/EventSessionItem.tsx
  src/events/page/sessions/EventSessions.tsx
  src/services/hooks/useSession.ts
  src/utils/diffDays.ts
  src/utils/timeFormats.ts
Labels: bug, enhancement

#12 feat: Notifications system
  .gitignore
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/auth/LoginForm.tsx
  src/components/AppSnackbar.tsx
  src/conferencehall/ConferenceHallEventsPicker.tsx
  src/context/SnackBarProvider.tsx
  src/events/list/EventsScreen.tsx
  src/events/new/NewEventDialog.tsx
  src/hooks/notificationHook.ts
Labels: enhancement, good first issue

#19 Add formats edition + re-import from CH feature
  src/components/ConfirmDialog.tsx
  src/conferencehall/firebase/getConferenceHallProposals.ts
  src/conferencehall/firebase/loadFromConferenceHallUtils.ts
  src/conferencehall/hooks/useConferenceHallProposals.tsx
  src/events/actions/addNewEvent.ts
  src/events/actions/conferenceHallUtils/importSessions.ts
  src/events/actions/conferenceHallUtils/importSpeakers.ts
  src/events/actions/conferenceHallUtils/mapFromConferenceHallToConferenceCenter.ts
  src/events/actions/deleteSessionsAndSpeakers.ts
  src/events/actions/reImportSessionsSpeakersFromConferenceHall.ts
  src/events/page/sessions/EventSessionItem.tsx
  src/events/page/sessions/EventSessions.tsx
  src/events/page/settings/EventSettings.tsx
  src/events/page/settings/components/FormatsFields.tsx
  src/events/page/settings/mapEventSettingsFormToMutateObject.ts
  src/events/page/speakers/EventSpeakerItem.tsx
  src/services/converters.ts
  src/services/firebase.ts
Labels: enhancement

#22 Add APIs urls
  .firebase/cors.json
  firebase.json
  firebase.storage.rules
  src/context/SnackBarProvider.tsx
  src/events/actions/addNewEvent.ts
  src/events/actions/deleteSessionsAndSpeakers.ts
  src/events/actions/getSessions.ts
  src/events/actions/getSpeakers.ts
  src/events/actions/updateWebsiteActions/getFilesNames.ts
  src/events/actions/updateWebsiteTriggerWebhooksAction.ts
  src/events/page/EventLayout.tsx
  src/events/page/EventRouter.tsx
  src/events/page/settings/EventSettings.tsx
  src/events/page/settings/components/EventAPIFilePaths.tsx
  src/events/page/settings/mapEventSettingsFormToMutateObject.ts
  src/services/firebase.ts
  src/types.ts
Labels: enhancement

#25 New proposals picker for ConferenceHall + new button to import specific talks after the event is created
  package-lock.json
  package.json
  src/components/AppSnackbar.tsx
  src/components/RequireConferenceHallConnections.tsx
  src/conferencehall/components/ConferenceHallProposalsPicker.tsx
  src/conferencehall/components/ConferenceHallProposalsPickerConnected.tsx
  src/conferencehall/hooks/useFakeConferenceHallProposals.ts
  src/events/actions/deleteSessionsAndSpeakers.ts
  src/events/actions/sessions/addSessionsFromCH.ts
  src/events/actions/sessions/getSessions.ts
  src/events/actions/sessions/updateSession.ts
  src/events/actions/updateWebsiteActions/updateWebsiteTriggerWebhooksAction.ts
  src/events/new/NewEventDialog.tsx
  src/events/page/EventLayout.tsx
  src/events/page/schedule/EventSchedule.tsx
  src/events/page/sessions/EventSessions.tsx
  src/events/page/sessions/components/SessionsImporterFromConferenceHallDialog.tsx
  src/utils/getRandomEnum.ts
Labels: enhancement

#29 Speaker edition
  src/events/actions/conferenceHallUtils/mapFromConferenceHallToConferenceCenter.ts
  src/events/actions/updateWebsiteActions/updateWebsiteTriggerWebhooksAction.ts
  src/events/page/EventRouter.tsx
  src/events/page/sessions/EventSessionForm.tsx
  src/events/page/speakers/EventSpeaker.tsx
  src/events/page/speakers/EventSpeakerForm.tsx
  src/events/page/speakers/EventSpeakers.tsx
  src/events/page/speakers/NewSpeaker.tsx
  src/events/page/speakers/SpeakerSocials.tsx
  src/types.ts
Labels: enhancement

#31 Small UI tweeks in Schedule
  src/events/page/schedule/components/SessionCard.tsx
  src/events/page/schedule/scheduleConstants.ts
  src/services/hooks/useSessions.ts
Labels: enhancement

#34 Add color to SessionCard & category
  src/events/actions/addNewEvent.ts
  src/events/page/schedule/components/SessionCard.tsx
  src/events/page/settings/components/CategoriesFields.tsx
  src/events/page/settings/mapEventSettingsFormToMutateObject.ts
  src/services/hooks/useSessions.ts
  src/types.ts
Labels: enhancement
